import type { Metadata } from "next";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const title = "Terms of Service | M&A Business Advisors";
const description =
  "Terms of Service for M&A Business Advisors (Avis USA, LLC), including SMS messaging terms.";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL;

export const metadata: Metadata = {
  ...(siteUrl ? { metadataBase: new URL(siteUrl) } : {}),
  title,
  description,
  openGraph: { title, description, type: "website" },
};

export default function Terms() {
  return (
    <>
      <Navbar />
      <main className="min-h-screen bg-[#FAFAF6]">
        <section className="py-20 md:py-28 px-4 md:px-6">
          <div className="max-w-3xl mx-auto">
            <p className="text-xs uppercase tracking-widest text-[#A07850] font-medium mb-4">
              Legal
            </p>
            <h1 className="text-4xl md:text-5xl font-[family-name:var(--font-cormorant)] font-light text-[#1C1C1A] mb-3 leading-tight">
              Terms of Service
            </h1>
            <p className="text-sm text-[#6B6B65] mb-12">Last updated June 17, 2026</p>

            <div className="space-y-8 text-[#3A3A35] leading-relaxed">
              <p>
                These Terms of Service govern your use of the website and services of M&amp;A Business Advisors, operated by Avis USA, LLC (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By accessing this website or contacting us, you agree to these terms.
              </p>

              <Section title="1. Our Services">
                <p>
                  M&amp;A Business Advisors provides merger and acquisition advisory services, including business valuation, exit planning, and connecting business owners with potential buyers. Information and tools provided on this site, including the Claude Exit System, are for general informational purposes and do not constitute financial, legal, or tax advice.
                </p>
              </Section>

              <Section title="2. SMS / Text Messaging Terms">
                <p>
                  By providing your phone number and opting in through a form on this website, you consent to receive text messages from M&amp;A Business Advisors (Avis USA, LLC) related to your inquiry, appointments, and our services. These may include informational, transactional, and promotional messages, possibly sent using automated technology.
                </p>
                <ul className="list-disc pl-5 space-y-2 mt-3">
                  <li>Message frequency varies.</li>
                  <li>Message and data rates may apply.</li>
                  <li>Consent is not a condition of any purchase.</li>
                  <li>Reply <strong>STOP</strong> at any time to unsubscribe. Reply <strong>HELP</strong> for help.</li>
                </ul>
                <p className="mt-3">
                  We do not sell, rent, or share your mobile opt-in information or phone number with third parties or affiliates for their marketing purposes. Mobile information is used solely to provide the services you requested.
                </p>
              </Section>

              <Section title="3. Use of the Website">
                <p>
                  You agree to use this website lawfully and not to misuse the tools, content, or forms provided. We may modify, suspend, or discontinue any part of the site at any time without notice.
                </p>
              </Section>

              <Section title="4. No Guarantees">
                <p>
                  Valuations, estimates, and analyses generated by our tools are based on the information you provide and are not guarantees of any outcome, sale price, or transaction. Actual results depend on many factors outside our control.
                </p>
              </Section>

              <Section title="5. Limitation of Liability">
                <p>
                  To the maximum extent permitted by law, Avis USA, LLC is not liable for any indirect, incidental, or consequential damages arising from your use of this website or our services.
                </p>
              </Section>

              <Section title="6. Contact">
                <p>
                  Avis USA, LLC (M&amp;A Business Advisors)<br />
                  5307 Metzger Ct, Sugar Land, TX 77479<br />
                  Email: <a className="text-[#A07850] hover:underline" href="mailto:sunny@mabusinessadvisors.com">sunny@mabusinessadvisors.com</a><br />
                  Phone: <a className="text-[#A07850] hover:underline" href="tel:+18327124162">(832) 712-4162</a>
                </p>
              </Section>
            </div>
          </div>
        </section>
      </main>
      <Footer linkedinUrl="https://www.linkedin.com/in/sumit-d/" />
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="text-xl font-medium text-[#1C1C1A] mb-3">{title}</h2>
      {children}
    </div>
  );
}
